### ISSUE TITLE
About DepthMapFactor

### ISSUE THREAD

**Issue by HJMGARMIN** [eliabntt/GRADE_data#2]
If I play the bags using ORB-SLAM, what is the DepthMapFactor? 1000.0 or 1.0?

**Comment by eliabntt** [comment]
I don't know what you are using. Rosbags should have 1 as depth factor (@Kyle-Xu001 can you confirm?) if you don't extract RGB and depth using our tools as explained [here](https://github.com/robot-perception-group/GRADE_tools/tree/main)

**Comment by HJMGARMIN** [comment]
I am sorry for my vague expression. I want to evaluate the RGBD ang RGBD-IMU modes of ORB-SLAM3 the dataset. If I use ROS to run ORB-SLAM3, the DepthMapFactor of yaml file should be set to 1.0. Do you mean this?

**Comment by eliabntt** [comment]
I cannot triple check right now, but it should be 1, since [here](https://github.com/robot-perception-group/GRADE_tools/blob/main/preprocessing/src/model/sensor_model.py#L181) there is no such factor. Either you wait for the @Kyle-Xu001 answer, or you can check manually by loading the bag with python, grasping a message, convert it using cv-bridge, and check. Depth will be between 0 and 3.5 meters (excluding nans and infs).

**Comment by Kyle-Xu001** [comment]
'DepthMapFactor' is mostly used for saving/loading depth maps in an image format (eg. PNG, JPG). In this case, 'DepthMapFactor' should be 1.0, since depth maps are directly obtained from rosbags.
